spring.application.name=svc-artisans
server.port=${PORT:8081}
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost:5432}/${DB_DATABASE:artisansSvc}
spring.datasource.username=${DB_USERNAME:harryjosecastrorodriguez}
spring.datasource.password=${DB_PASSWORD:secret}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=debug

# Microservice connection with msvc-catalog
msvc.catalog.url=${CATALOG_URL:localhost:8082/api/v1}

# Payment processing with Stripe
stripe.key.secret=sk_test_51QD4mfEXBhH6CH90ksLJ8zqtgsD9a3iJ3cWKxcZf0ADFvPJUTMBwOlfRHMnQ4s4BU2ULyt68bHuL5idKko0TBcCE00SAmkV9WX

# Kubernetes configuration
spring.cloud.kubernetes.secrets.enable-api=true
spring.cloud.kubernetes.discovery.all-namespaces=true

# Documentation Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html