apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: service-list-role
rules:
  - apiGroups: [""]
    resources: ["services", "endpoints"]
    verbs: ["list", "get", "watch"]

