apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc-artisans
spec:
  replicas: 1
  selector:
    matchLabels:
      app: svc-artisans
  template:
    metadata:
      labels:
        app: svc-artisans
    spec:
      containers:
        - image: harrycas/svc-artisans-arm:latest
          name: svc-artisans-arm
          ports:
            - containerPort: 8081
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: svc-artisans
                  key: port
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: svc-artisans
                  key: db_host
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: svc-artisans
                  key: database
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: svc-artisans
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: svc-artisans
                  key: password
            - name: CATALOG_URL
              valueFrom:
                configMapKeyRef:
                  name: svc-artisans
                  key: catalog_url