apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres15
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres15
  template:
    metadata:
      labels:
        app: postgres15
    spec:
      containers:
        - image: postgres:15-alpine
          name: postgres15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: harryjosecastrorodriguez
            - name: POSTGRES_PASSWORD
              value: root
            - name: POSTGRES_DB
              value: artisansCatalog
          volumeMounts:
            - name: data-postgres
              mountPath: /var/lib/postgresql/data  # This has to be like that
      volumes:
        - name: data-postgres
          persistentVolumeClaim:
            claimName: postgres-pvc

# We use the colons because we can have multiple instances in general
