apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres15-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres15-v1
  template:
    metadata:
      labels:
        app: postgres15-v1
    spec:
      containers:
        - image: postgres:15-alpine
          name: postgres15-v1
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: harryjose
            - name: POSTGRES_PASSWORD
              value: secret
            - name: POSTGRES_DB
              value: artisans  # v1 is for the svc-artisans
          volumeMounts:
            - name: data-postgres-v1
              mountPath: /var/lib/postgresql/data  # This has to be like that
      volumes:
        - name: data-postgres-v1
          persistentVolumeClaim:
            claimName: postgresv1-pvc
