apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresv1-pv
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/lib/postgresql/data-v1
    type: DirectoryOrCreate