apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresv1-pvc
spec:
  volumeName: postgresv1-pv
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi