apiVersion: v1
kind: Service
metadata:
  name: postgres15
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: postgres15
  type: ClusterIP

# The label 'app' can be replaced with any other label like 'role'
# But it has to be the same in the deployment and service